# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "local" {
    path = "C:/Users/utsa.chatterjee/Downloads/Repo/catalog/csp-databricks/states/sbx/delta-share/terraform.tfstate"
  }
}
